### ISSUE TITLE
TestdataButtons not found

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/gwiki#3]
Tested with https://github.com/mambax7/gwiki and Xoops 2.5.11 latest version.

When I check "Yes" to "Show Sample Button?" in the preferences, I get an error:

`Error: Class 'XoopsModules/Gwiki/Common/TestdataButtons' not found in file /modules/gwiki/admin/index.php line 36`

Thanks again for your help ;-)

___
My config:

Apache/2.4.18 (Ubuntu)
PHP version 7.4.9
MySQLi extension mysqlnd 7.4.9

**Comment by mambax7** [comment]
On my local PC I can't reproduce it.  Was this a fresh installation, or an update of an existing one? If an update, could you try a fresh installation? 

I'll try to test it on our demo server to see if I can reproduce it there...

**Comment by mambax7** [comment]
BTW - There is currently no need for the Sample Data button, because Gwiki has already the "Help Pages" that could be imported to test the functionality

testsite/modules/gwiki/admin/pages.php?op=addhelp

**Comment by cesagonchu** [comment]
It's a new installation but when I had the first bug, I uninstalled and reinstalled the module, after clearing the caches from the admin side maintenance (modules/system/admin.php?fct=maintenance).
EDIT: But I got this error when I first installed the module. Xoops is also new.

**Comment by cesagonchu** [comment]
Could the problem come from the fact that I installed on the ftp the Xoops as an admin while I sent the module on the ftp as a simple user?

**Comment by mambax7** [comment]
I was able to reproduce that error on our Demo site, but I'm not sure right now why it is happening, because the the TestdataButtons class is there. I'll investigate it and keep you post it

And no, the the FTP should not have any impact on it...

**Comment by mambax7** [comment]
The problem was that the folder was "common" instead of "Common" with capital "C" - just rename it and it will work now
