### ISSUE TITLE
GwikiPage.php

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/gwiki#4]
When I want to create a page, on the user side (/modules/gwiki/edit.php?page=WikiHome), I get this error:

`Notice: Trying to access array offset on value of type bool in file /modules/gwiki/class/GwikiPage.php line 853`

___
My config:

Apache/2.4.18 (Ubuntu)
PHP version 7.4.9
MySQLi extension mysqlnd 7.4.9

**Comment by cesagonchu** [comment]
Can you replicate it?
The module works despite this error but you might as well fix it when you have time of course :-)

**Comment by mambax7** [comment]
This was fixed here: https://github.com/mambax7/gwiki/commit/14f810787a2adea5dee4cd2d7859c7e11f3a97c9
