### ISSUE TITLE
Unknown: implode() deprecated

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/gwiki#5]
When I make a modification in the "Namespaces" tab on the administration side (modules/gwiki/admin/prefixes.php?pid=1&op=edit), I get this error:
`Unknown: implode(): Passing glue string after array is deprecated. Swap the parameters in file /modules/gwiki/admin/prefixes.php line 227`

___
My config:

Apache/2.4.18 (Ubuntu)
PHP version 7.4.9
MySQLi extension mysqlnd 7.4.9

**Comment by mambax7** [comment]
You can ignore all "deprecated" warnings - the module will work fine with them, it's only an info for the developers.
